[book]
title = "Rando Doc"
authors = ["Ibot02", "Henny022"]
description = "Documentation about the randomizer"
language = "en"


[build]
create-missing = false

[output.html]
git-repository-url = "https://github.com/Henny022/rando-doc"
edit-url-template = "https://github.com/Henny022/rando-doc/edit/main/{path}"
